version : '3'
services : 
    web:
        build: ./web
        ports:
            - "8081:8080"
    db:
        image: postgres:12.6
        environment:
            POSTGRES_USER : postgres
            POSTGRES_PASSWORD : 1234
            POSTGRES_DB : test
